---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: graphql
spec:
  template:
    spec:
      containers:
        - name: graphql
          image: shokohsc/moleculer-ouistity
          env:
            - name: APP_GRAPHQL_ONE_MINUTE_CACHE_TTL
              value: "5"
            - name: APP_GRAPHQL_ONE_DAY_CACHE_TTL
              value: "5"
            - name: APP_GRAPHQL_ONE_YEAR_CACHE_TTL
              value: "5"
          #   - name: APP_NATS_HOSTNAME
          #     value: nats.nats
          #   - name: APP_RETHINKDB_HOSTNAME
          #     value: rethinkdb.rethinkdb
          args:
            - --hot
            - services/graphql-gateway.service.js
          volumeMounts:
            - name: nfs-shared
              mountPath: /usr/app/assets/data/archives/weekly
            - name: nfs-wd-zarya
              mountPath: /usr/app/assets/data/archives/comics
      volumes:
        - name: nfs-shared
          nfs:
            server: nfs-shared.nfs-shared.svc.cluster.local
            path: /weekly
        - name: nfs-wd-zarya
          nfs:
            server: nfs-wd-zarya.nfs-wd-zarya.svc.cluster.local
            path: /comics
