---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: graphql
spec:
  template:
    spec:
      containers:
        - name: graphql
          image: shokohsc/moleculer-ouistity
          env:
            - name: APP_GRAPHQL_DEFAULT_CACHE_TTL
              value: "0"
            - name: APP_GRAPHQL_FOLDER_CACHE_TTL
              value: "0"
            - name: APP_GRAPHQL_BOOKS_CACHE_TTL
              value: "0"
          #   - name: APP_NATS_HOSTNAME
          #     value: nats.nats
          #   - name: APP_RETHINKDB_HOSTNAME
          #     value: rethinkdb.rethinkdb
          args:
            - --hot
            - services/graphql-gateway.service.js
          volumeMounts:
            - name: nfs-shared
              mountPath: /usr/app/assets/data/archives/weekly
            - name: nfs-wd2to
              mountPath: /usr/app/assets/data/archives/comics
      volumes:
        - name: nfs-shared
          nfs:
            server: nfs-shared.nfs-shared
            path: /weekly
        - name: nfs-wd2to
          nfs:
            server: nfs-wd2to.nfs-wd2to
            path: /comics
