---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apollo
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/group: dev
    forecastle.stakater.com/appName: apollo
spec:
  rules:
  - host: apollo.ouistity.shokohsc.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: graphql
            port:
              number: 7000
  tls:
  - hosts:
    - apollo.ouistity.shokohsc.home
    secretName: apollo-cert
