version: "3.7"

services:

  thumbor:
    image: "minimalcompact/thumbor"
    restart: "unless-stopped"
    networks:
      - "public"
    ports:
      - "8880:80/tcp"

  rethinkdb:
    image: "rethinkdb:2.4.1"
    restart: "unless-stopped"
    volumes:
      - "rethinkdb_data:/data"
    networks:
      - "public"
    ports:
      - "8080:8080/tcp"
      - "28015:28015/tcp"

  redis:
    image: "redis:6.2.6"
    restart: "unless-stopped"
    networks:
      - "public"
    ports:
      - "6379:6379/tcp"

  nats:
    image: "nats:2.2.0-alpine"
    restart: "unless-stopped"
    command:
      - "--debug"
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
    networks:
      - "public"
    ports:
      - "4222:4222/tcp"

  rabbitmq:
    image: "rabbitmq:3.7.17-management-alpine"
    restart: "unless-stopped"
    environment:
      RABBITMQ_ERLANG_COOKIE: "${APP_RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${APP_RABBITMQ_USERNAME}"
      RABBITMQ_DEFAULT_PASS: "${APP_RABBITMQ_PASSWORD}"
    networks:
      - "public"
    ports:
      - "5672:5672/tcp"
      - "15672:15672/tcp"

volumes:

  mongodb_data:
  rethinkdb_data:

networks:

  public:
    name: public
