version: "3.7"

services:

  mongodb:
    image: "bitnami/mongodb:4.4"
    volumes:
      - "mongodb_data:/bitnami"
    networks:
      - "public"
    ports:
      - "27017:27017/tcp"

  nats:
    image: "nats:2.2.0-alpine"
    command:
      - "--debug"
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
    networks:
      - "public"
    ports:
      - "4222:4222/tcp"

volumes:

  mongodb_data:

networks:

  public:
    name: public
