version: "3.7"

services:

  nats:
    image: "nats:2.2.0-alpine"
    command:
      - "--debug"
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
    networks:
      - "public"
    ports:
      - "4222:4222/tcp"

networks:

  public:
    name: public
