version: "3.7"

services:

  rethinkdb:
    image: rethinkdb:2.4.0
    networks:
      - "public"
    volumes:
      - rethinkdb_data:/data
    ports:
      - "28015:28015/tcp"
      - "29015:29015/tcp"
      - "8080:8080/tcp"

  nats:
    image: "nats:2.2.0-alpine"
    command:
      - "--debug"
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
    networks:
      - "public"
    ports:
      - "4222:4222/tcp"

volumes:

  rethinkdb_data:

networks:

  public:
    name: public
