apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: ouistity
build:
  artifacts:
  - image: shokohsc/moleculer-ouistity
    context: .
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'services/**/*.js'
        dest: .
      - src: 'mixins/*.js'
        dest: .
deploy:
  kustomize:
    paths:
      - k8s/base
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
      - image: shokohsc/moleculer-ouistity
  - name: shokohsc
    build:
      cluster:
        namespace: kaniko
        pullSecretName: kaniko-secret
        dockerConfig:
          secretName: kaniko-secret
      artifacts:
      - image: shokohsc/moleculer-ouistity
    deploy:
      kustomize:
        paths:
          - k8s/overlays/shokohsc
