apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: ouistity
build:
  artifacts:
  - image: shokohsc/ouistity
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
      - image: shokohsc/ouistity
        context: .
        docker:
          buildArgs:
            ENV: development
        sync:
          manual:
          - src: 'services/**/*.js'
            dest: .
