---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: archives
spec:
  template:
    spec:
      containers:
        - name: archives
          image: shokohsc/moleculer-ouistity
          env:
            - name: APP_GLOBAL_GATEWAY_URL
              value: https://api.ouistity.shokohsc.home
            # - name: APP_NATS_HOSTNAME
            #   value: nats.nats
          args:
            - --hot
            - services/archives.service.js
          volumeMounts:
            - name: nfs-shared
              mountPath: /usr/app/assets/data/archives/weekly
            - name: nfs-wd-zarya
              mountPath: /usr/app/assets/data/archives/comics
      volumes:
        - name: nfs-shared
          nfs:
            server: nfs-shared.nfs-shared.svc.cluster.local
            path: /weekly
        - name: nfs-wd-zarya
          nfs:
            server: nfs-wd-zarya.nfs-wd-zarya.svc.cluster.local
            path: /comics
