---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ouistity-graphql-gateway
spec:
  selector:
    matchLabels:
      app: ouistity-graphql-gateway
  template:
    metadata:
      labels:
        app: ouistity-graphql-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "5050"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: ouistity-graphql-gateway
          image: shokohsc/moleculer-ouistity
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: APP_NATS_HOSTNAME
              value: nats
          args:
            - --hot
            - services/graphql-gateway.service.js
          ports:
            - name: http
              containerPort: 7000
              protocol: TCP
