---
apiVersion: v1
kind: Service
metadata:
  name: ouistity-graphql-gateway
  labels:
    app: ouistity-graphql-gateway
spec:
  type: ClusterIP
  ports:
    - port: 7000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ouistity-graphql-gateway
