---
apiVersion: v1
kind: Service
metadata:
  name: archives
  labels:
    app: archives
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: archives
