---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: api
          image: shokohsc/moleculer-ouistity
          env:
            - name: APP_GLOBAL_GATEWAY_URL
              value: https://api.ouistity.shokohsc.home
            - name: APP_IMAGE_CACHE_TTL
              value: "30"
          args:
            - --hot
            - services/api-gateway.service.js
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - api
                  - archives
                  - books
                  - graphql
                  - pages
              topologyKey: kubernetes.io/hostname
