---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: api
          image: shokohsc/moleculer-ouistity
          env:
            - name: APP_GLOBAL_GATEWAY_URL
              value: https://api.ouistity.shokohsc.home
            - name: APP_NATS_HOSTNAME
              value: nats.nats
          volumeMounts:
            - name: nfs-shared
              mountPath: /usr/app/assets/data/archives/weekly
            - name: nfs-wd2to
              mountPath: /usr/app/assets/data/archives/comics
      volumes:
        - name: nfs-shared
          nfs:
            server: nfs-shared.nfs-shared
            path: /weekly
        - name: nfs-wd2to
          nfs:
            server: nfs-wd2to.nfs-wd2to
            path: /comics
