---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ouistity-api-gateway
spec:
  selector:
    matchLabels:
      app: ouistity-api-gateway
  template:
    metadata:
      labels:
        app: ouistity-api-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "5050"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: ouistity-api-gateway
          image: shokohsc/ouistity
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: APP_GLOBAL_GATEWAY_URL
              value: http://api.cluster.local
            - name: APP_NATS_HOSTNAME
              value: nats
          args:
            - --hot
            - services/api-gateway.service.js
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
            - name: apollo
              containerPort: 7000
              protocol: TCP
            - name: metrics
              containerPort: 5050
              protocol: TCP
