---
apiVersion: v1
kind: Service
metadata:
  name: ouistity-books
  labels:
    app: ouistity-books
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
    - port: 5050
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: ouistity-books
