---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ouistity
spec:
  selector:
    matchLabels:
      app: ouistity
  template:
    metadata:
      labels:
        app: ouistity
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: ouistity
          image: shokohsc/ouistity
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: APP_GLOBAL_GATEWAY_URL
              value: http://cluster.local
            - name: APP_MONGODB_HOSTNAME
              value: mongodb
            - name: APP_NATS_HOSTNAME
              value: nats
          args:
            - --hot
            - services
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
            - name: apollo
              containerPort: 7000
              protocol: TCP
            - name: metrics
              containerPort: 5050
              protocol: TCP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: mongodb
          image: bitnami/mongodb:4.4
          ports:
            - name: http
              containerPort: 27017
              protocol: TCP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nats
spec:
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: nats
          image: nats:2.2.0-alpine
          args:
            - "--debug"
            - "--cluster"
            - "nats://0.0.0.0:6222"
            - "--http_port"
            - "8222"
            - "--port"
            - "4222"
          ports:
            - name: http
              containerPort: 4222
              protocol: TCP
