---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: mongodb
          image: bitnami/mongodb:4.4
          ports:
            - name: http
              containerPort: 27017
              protocol: TCP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongo-express
spec:
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: mongo-express
          image: mongo-express
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nats
spec:
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: nats
          image: nats:2.2.0-alpine
          args:
            - "--debug"
            - "--cluster"
            - "nats://0.0.0.0:6222"
            - "--http_port"
            - "8222"
            - "--port"
            - "4222"
          ports:
            - name: http
              containerPort: 4222
              protocol: TCP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: rabbitmq
          image: rabbitmq:3.7.17-management-alpine
          env:
            - name: RABBITMQ_ERLANG_COOKIE
              value: ""
            - name: RABBITMQ_DEFAULT_USER
              value: rabbitmq
            - name: RABBITMQ_DEFAULT_PASS
              value: changeme
          ports:
            - name: http
              containerPort: 5672
              protocol: TCP
            - name: admin
              containerPort: 15672
              protocol: TCP
