---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: thumbor
spec:
  selector:
    matchLabels:
      app: thumbor
  template:
    metadata:
      labels:
        app: thumbor
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: thumbor
          image: minimalcompact/thumbor
          env:
            - name: THUMBOR_PORT
              value: "80"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rethinkdb
spec:
  selector:
    matchLabels:
      app: rethinkdb
  template:
    metadata:
      labels:
        app: rethinkdb
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: rethinkdb
          image: rethinkdb:2.4.1
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: rethinkdb
              containerPort: 28015
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rethinkdb
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rethinkdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nats
spec:
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: nats
          image: nats:2.2.0-alpine
          args:
            - "--debug"
            - "--cluster"
            - "nats://0.0.0.0:6222"
            - "--http_port"
            - "8222"
            - "--port"
            - "4222"
          ports:
            - name: http
              containerPort: 4222
              protocol: TCP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: rabbitmq
          image: rabbitmq:3.7.17-management-alpine
          env:
            - name: RABBITMQ_ERLANG_COOKIE
              value: ""
            - name: RABBITMQ_DEFAULT_USER
              value: rabbitmq
            - name: RABBITMQ_DEFAULT_PASS
              value: changeme
          ports:
            - name: http
              containerPort: 5672
              protocol: TCP
            - name: admin
              containerPort: 15672
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rabbitmq
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
