---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-express
spec:
  rules:
  - host: mongo.cluster.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mongo-express
            port:
              number: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq
spec:
  rules:
  - host: rabbitmq.cluster.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rabbitmq
            port:
              number: 15672
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
spec:
  rules:
  - host: api.cluster.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ouistity-api-gateway
            port:
              number: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apollo
spec:
  rules:
  - host: apollo.cluster.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ouistity-graphql-gateway
            port:
              number: 7000
