apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moleculer-ouistity
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

  - api-gateway/deployment.yaml
  - api-gateway/service.yaml

  - archives/deployment.yaml
  - archives/service.yaml

  - books/deployment.yaml
  - books/service.yaml

  - graphql-gateway/deployment.yaml
  - graphql-gateway/service.yaml

  - pages/deployment.yaml
  - pages/service.yaml
