---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: mongo-express
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    app: nats
spec:
  type: ClusterIP
  ports:
    - port: 4222
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nats
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: http
      protocol: TCP
      name: http
    - port: 15672
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    app: rabbitmq
