---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thumbor
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/group: dev
    forecastle.stakater.com/appName: ouistity-thumbor
spec:
  rules:
  - host: thumbor.ouistity.shokohsc.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: thumbor
            port:
              number: 80
  tls:
  - hosts:
    - thumbor.ouistity.shokohsc.home
    secretName: ouistity-thumbor-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rethinkdb
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/group: dev
    forecastle.stakater.com/appName: ouistity-rethinkdb
spec:
  rules:
  - host: rethinkdb.ouistity.shokohsc.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rethinkdb
            port:
              number: 8080
  tls:
  - hosts:
    - rethinkdb.ouistity.shokohsc.home
    secretName: ouistity-rethinkdb-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/group: dev
    forecastle.stakater.com/appName: ouistity-rabbitmq
spec:
  rules:
  - host: rabbitmq.ouistity.shokohsc.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rabbitmq
            port:
              number: 15672
  tls:
  - hosts:
    - rabbitmq.ouistity.shokohsc.home
    secretName: ouistity-rabbitmq-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/group: dev
    forecastle.stakater.com/appName: ouistity-api-gateway
spec:
  rules:
  - host: api.ouistity.shokohsc.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ouistity-api-gateway
            port:
              number: 5000
  tls:
  - hosts:
    - api.ouistity.shokohsc.home
    secretName: ouistity-api-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apollo
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/group: dev
    forecastle.stakater.com/appName: ouistity-apollo
spec:
  rules:
  - host: apollo.ouistity.shokohsc.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ouistity-graphql-gateway
            port:
              number: 7000
  tls:
  - hosts:
    - apollo.ouistity.shokohsc.home
    secretName: ouistity-apollo-cert
