---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thumbor
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/group: dev
    forecastle.stakater.com/appName: thumbor
spec:
  rules:
  - host: thumbor.ouistity.shokohsc.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: thumbor
            port:
              number: 80
  tls:
  - hosts:
    - thumbor.ouistity.shokohsc.home
    secretName: thumbor-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rethinkdb
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/group: dev
    forecastle.stakater.com/appName: rethinkdb
spec:
  rules:
  - host: rethinkdb.ouistity.shokohsc.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rethinkdb
            port:
              number: 8080
  tls:
  - hosts:
    - rethinkdb.ouistity.shokohsc.home
    secretName: rethinkdb-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/group: dev
    forecastle.stakater.com/appName: rabbitmq
spec:
  rules:
  - host: rabbitmq.ouistity.shokohsc.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rabbitmq
            port:
              number: 15672
  tls:
  - hosts:
    - rabbitmq.ouistity.shokohsc.home
    secretName: rabbitmq-cert
