---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
data:
  host: YW1xcDovL3JhYmJpdG1xOmNoYW5nZW1lQHJhYmJpdG1xLm1vbGVjdWxlci1vdWlzdGl0eTo1NjcyLw==
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-conn
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq
      key: host
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: books
spec:
  scaleTargetRef:
    name: books
  pollingInterval: 10
  cooldownPeriod:  10
  # idleReplicaCount: 0
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: moleculer.archives-domain-generate-book.queue
      mode: QueueLength
      value: "100"
    authenticationRef:
      name: rabbitmq-conn
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: pages
spec:
  scaleTargetRef:
    name: pages
  pollingInterval: 10
  cooldownPeriod:  10
  # idleReplicaCount: 0
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: moleculer.archives-domain-generate-book-pages-catalog.queue
      mode: QueueLength
      value: "1000"
    authenticationRef:
      name: rabbitmq-conn
