apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moleculer-ouistity
bases:
  - ../../base
  - keda.yaml
patchesStrategicMerge:
  - ingress.yaml

  - api/deployment.yaml
  - archives/deployment.yaml
  - books/deployment.yaml
  - graphql/deployment.yaml
  - pages/deployment.yaml
